### PR TITLE
Improvements to application form

### PR DESCRIPTION
**Pull request by chriswhawkins**
Plus a chance to look things over. This is tested and deployed but it felt like a good place for you to take a look.

### CODE REVIEW

**Comment by mewdriller** [comment]
> images are on dropbox: b2/client/elm

I saw that on the README, is that just source images or are the production assets stored there as well? I was thinking Surge probably did the asset hosting/CDN'ing.

**Comment by chriswhawkins** [comment]
Source images only on dropbox. I'll make that clearer next update. We have another task for improving images and storage/serving, though (presently just letting surge do whatever it does and only serving one size, etc). I'll ping you when I look into solutions @mewdriller

**Comment by mewdriller** [comment]
the-elm-inn--button-alignment

The alignment on the text baseline looks a little high. I'm not sure if that's just me seeing things, intentional, etc.

**Comment by mewdriller** [comment]
the-elm-inn--placeholder-color

The placeholder text color for the date input looks darker than  the others. I'm not sure if that's something we can style.

**Comment by mewdriller** [comment]
the-elm-inn--favicon

It looks like it's defaulting to the last `localhost` site I ran that had a favicon (AC Lens) so there's probably not one referenced/included. Is that something that's doable?

**Comment by mewdriller** [comment]
the-elm-inn--footer-position

When I open the page in a tallish browser window the footer doesn't quite hit the bottom. Once the "Apply" section is opened it does then hit the bottom and connect. The whitespace below the grey section looks a bit off to my eye. Maybe the footer should hit the bottom in the normal configuration too?

**Comment by mewdriller** [comment]
The PR itself looks great. I'm glad the Formspree options work on the free plan as well.

I had a few comments on the site as a whole since this is the first time I've checked-out/reviewed it in its entirety.

:shipit:

**Comment by chriswhawkins** [comment]
Thanks for PR'ing this @mewdriller - I created the following issues for the things you mentioned:
#17 Vertical alignment on Apply for job button
#16 Styling of date input placeholder text
#15 Favicon for website
#14 Fix footer to bottom of screen (on short screens)

I'll go ahead and close/merge this PR and address those issues separately. Thanks!

**Pull request merged**
